services:
  report-generation-service:
    build:
      context: ./report-generation-service
    ports:
      - "3001:3000" 
    environment:
      - DATABASE_URL=postgres://user:password@report-generation-db:5432/report_generation_db
    depends_on:
      - report-generation-db

  report-requester-service:
    build:
      context: ./report-requester-service
    ports:
      - "3002:3000" 
    environment:
      - DATABASE_URL=postgres://user:password@report-requester-db:5432/report_requester_db
    depends_on:
      - report-requester-db

  report-generation-db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: report_generation_db
    volumes:
      - report-generation-db-data:/var/lib/postgresql/data

  report-requester-db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: report_requester_db
    volumes:
      - report-requester-db-data:/var/lib/postgresql/data

volumes:
  report-generation-db-data:
  report-requester-db-data: